### ISSUE TITLE
Data files are not correctly updated

### ISSUE THREAD

**Issue by xplosionmind** [scambifestival/pinosync#5]
By triggering updates, files are not correctly updated. For example, taking as a reference `2021 Program`, table `325` view `2549`: `2021-labs`.

![Screenshot from 2023-05-18 12-08-29](https://github.com/scambifestival/pinosync/assets/42862428/62d5723a-a71a-4f4a-a97a-664a7e735caf)

`2021-labs` should not have the `props` field displayed (maybe there are other incongruities but for the sake of simplicity I am using only this field). The screenshot below shows [the original table and its view on Pino](https://pino.scambi.org/database/61/table/325/2549).

![Screenshot from 2023-05-18 12-07-28](https://github.com/scambifestival/pinosync/assets/42862428/0456beb4-8db0-46ed-b822-a0a25c5b6346)

Nevertheless, both locally (when telling pinosync to sync files in `./new`) and [remotely (on GitHub)](https://github.com/scambifestival/scambi.org/blob/main/data/2021-labs.csv) the CSV files do not correspond to the Pino table.

![Screenshot from 2023-05-18 12-09-28](https://github.com/scambifestival/pinosync/assets/42862428/e0cd14c3-a017-4628-aa3f-93f80f3bd5bb)

![Screenshot from 2023-05-18 12-12-49](https://github.com/scambifestival/pinosync/assets/42862428/822b760e-a428-4e2c-856c-dd11d910692a)

**Comment by 2ale2** [comment]
Apparently, the Baserow API uses the `view_id` parameter for ordering and filtering purposes only. In other words, all the table fields are included even if a `view_id` is given, cause it does not affect the set of included fields.

I also tried using a Python session with personal login, but Baserow has scraper protection.

If I'll not receive help from the Baserow forum on this, I'll add the `exclude` parameter in order to allow users choosing which fields will be excluded from the output table/view request.

Further details soon.

**Comment by xplosionmind** [comment]
Thanks @2ale2! Could you please commit in the meanwhile? I need to go on developing the integration…

**Comment by 2ale2** [comment]
Baserow support reached out: it's possibile to exclude hidden columns from the output file doing some API requests. I'll commit asap before applying the fixes for this issue, than I'll commit again after fixes are applied.

**Comment by 2ale2** [comment]
Last commit fixed this issue: now hidden columns in a view are automatically excluded from the output file unless they are explicitally added to the 'include' parameter.

In particular, the script asks for _field options_ of a given view in order to know which columns are hidden.
Please note that you must indicate a VIEW_ID in _tablesInfos.yml_ in order to exclude hidden columns.

I hope we will not find any other bug..
